frontend/controllers/CartController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\Products;
use common\models\ProductsSearch;
use common\models\ConfirmedOrders;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use common\models\LoginForm;
use yii\web\Session;

/**
 * CartController implements the CRUD actions for Products model.
 */
class CartController extends Controller
{
    
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Products models.
     * @return mixed
     */
    public function actionIndex() {
        $session = Yii::$app->session;
        $products = [];
        if($session['total_items'] > 0){
            $products = self::getProductsInCart();
        }
        return $this->render('index', [
            'products' => $products,
        ]);
    }
    
    /**
     * Get all products in users cart (Confirmed or in Session).
     * @return array $products_in_cart products in cart data.
     * @throws NotFoundHttpException if the model cannot be found
     */
    private function getProductsInCart(){
        $products_in_cart = self::getSessionOrders();
        
        if(!Yii::$app->user->isGuest){ 
            $confirmed_orders = ConfirmedOrders::getUserComfirmedOrders();
            foreach($confirmed_orders as $order) {
                $products_in_cart[] = $this->getOrderedProductData($order, 'confirmed');
            }
        }
        
        return $products_in_cart;
    }
    
    /**
     * Get products added to cart during users Session (but still not confirmed).
     * @return array $cart_products not confirmed products in cart data.
     * @throws NotFoundHttpException if the model cannot be found
     */
    private function getSessionOrders(){
        $order_ids = self::getProductdIdsInSession();
        $sessios_products = Products::getProductsBySpecificIds($order_ids);
        foreach ($sessios_products as $product){
            $cart_products[] =  self::getOrderedProductData($product);
        }
        return $cart_products;
    }
    
    /**
     * Takes all orders added to Session, extracts product ids and returns them.
     * @return array $order_ids ordered (not confirmed) product ids.
     * @throws NotFoundHttpException if the model cannot be found
     */
    private function getProductdIdsInSession(){
        $session = Yii::$app->session;
        $order_ids = [];
        foreach($session as $session_name => $value){
            $session_name_data = explode("_", $session_name);
            $name = $session_name_data[0];
            if($name === 'products'){
                $order_ids[] = $session_name_data[1];
            }
        }
        return $order_ids;
    }
    
    private function getOrderedProductData($order, $order_type = 'not_confirmed'){
        switch ($order_type){
            case 'not_confirmed':
                $session = Yii::$app->session;
                $price = $order->price;
                $amount = $session['products_'.$order->id];
                $confirmed = 0;
                break;
            case 'confirmed':
                $amount = $order->order_amount;
                $price = $order->confirmedOrdersData->price;
                $confirmed = 1;
                break;
        }
        
        return [
            'id' => $order->id,
            'title' => $order->uniqueProduct->title,
            'amount' => $amount,
            'price' => $price,
            'img' => $order->uniqueProduct->img,
            'confirmed' => $confirmed,
        ];
    }


    /**
     * Displays a single Products model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id, $numb)
    {
        return $this->redirect(['/bids/index', 'id' => $id , 'numb' => $numb]);
    }

    /**
     * Creates a new Products model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Products();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->product_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Products model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->product_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Products model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Products model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Products the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Products::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('app', 'The requested page does not exist.'));
    }
    
    //--------- ADD TO CART (beginning)------------\\
    public function actionAdd($id)
    {
        $model = $this->findModel($id);
        //add product to cart if product exists;
        (empty($model->id))? : self::addToCart($model);
        
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    private function addToCart($model)
    {
        $session = Yii::$app->session;
        $product_order_amount = (!isset($session['products_'.$model->id])) ? 1 : $session['products_'.$model->id] + 1;
        $add_up_numb = ($model->amount >= $product_order_amount) ? 1 : 0; 
        $session['products_'.$model->id] += $add_up_numb;
        $session['total_items'] += $add_up_numb;
    }
    
    //--------- ADD TO CART (end)------------\\
    
    //--------- MINUS FROM CART (beginning)------------\\
    public function actionMinus($id)
    {
        $model = $this->findModel($id);
        //add product to cart if product exists;
        if(!empty($model->id)){
            self::minusFromCart($model);
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    private function minusFromCart($model)
    {
        $session = Yii::$app->session;
        if(isset($session['products_'.$model->id])){
            $product_order_amount = $session['products_'.$model->id];
            $minus_down_numb = 1; 
            $session['products_'.$model->id] -= $minus_down_numb;
            $session['total_items'] -= $minus_down_numb;
            if($product_order_amount < 2){
                unset($session['products_'.$model->id]);
            }
        }
    }
    
    //--------- MINUS FROM CART (end)------------\\
    
    //--------- CONFIRM PRODUCT (beginning)------------\\
    public function actionConfirm($id, $numb){
        $session = Yii::$app->session;
        $pro_model = $this->findModel($id);
        $conf_order_model  = new ConfirmedOrders();
        
        $conf_order_model->attributes = [
            'product_id' => $id,
            'order_numb' => $numb,
            'order_amount' => $session['products_'.$id. "_" . $numb],
            'order_price' => $pro_model->price,
            'user_ip' => self::getRealIpAddr(),
        ];
        if($conf_order_model->save()){
            $session['confirmed_'.$id.'_'.$numb] = $conf_order_model->id;
            return $this->redirect(['/bids/index', 'id' => $id , 'numb' => $numb]);
        }
        return $this->redirect(Yii::$app->request->referrer);
    }
    //--------- CONFIRM PRODUCT (end)------------\\
    
    
    private function getRealIpAddr()
    {
        if (!empty($_SERVER['HTTP_CLIENT_IP']))   //check ip from share internet
        {
          $ip=$_SERVER['HTTP_CLIENT_IP'];
        }
        elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR']))   //to check ip is pass from proxy
        {
          $ip=$_SERVER['HTTP_X_FORWARDED_FOR'];
        }
        else
        {
          $ip=$_SERVER['REMOTE_ADDR'];
        }
        return $ip;
    }
    
    
    public function actionPayment() 
    {
        if (Yii::$app->user->isGuest || !Yii::$app->request->isAjax) {
            return $this->goBack();
        }
        
        return $this->renderAjax('payment');
    }
}

frontend/views/cart/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\ProductsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="products-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'product_id') ?>

    <?= $form->field($model, 'product_title') ?>

    <?= $form->field($model, 'product_category_id') ?>

    <?= $form->field($model, 'product_price') ?>

    <?= $form->field($model, 'product_quantity') ?>

    <?php // echo $form->field($model, 'product_description') ?>

    <?php // echo $form->field($model, 'short_desc') ?>

    <?php // echo $form->field($model, 'product_img') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/cart/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\db\Query;
use yii\db\ActiveQuery;
use yii\web\Session;
use yii\bootstrap\Modal;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$session = Yii::$app->session;
$this->title = Yii::t('front-end', 'Cart');
$this->registerJsFile(
    '@web/js/cart.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
?>
<div class="products-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
    
    <?php
    $query = new Query();
    $provider = new ArrayDataProvider([
        'allModels' => $products,
        'pagination' => [
            'pageSize' => 10,
        ],
    ]);
    ?>
    <?= GridView::widget([
        'dataProvider' => $provider,
        'columns' => [
            [
                'class' => 'yii\grid\SerialColumn',
                'headerOptions' => ['style' => 'width:40px'],
            ],
            [
                'label' => Yii::t('front-end', 'Title'),
                'value' => function($model) {
                    return $model['title'];
                },
            ],
            [
                'label' => Yii::t('front-end', 'Amount'),
                'value' => function($model) {
                    return $model['amount'];
                },
                'headerOptions' => ['style' => 'width:80px'],
            ],
            [ 
                'label' => Yii::t('front-end', 'Item Price'),
                'value' => function($model) {
                    return $model['price'];
                },
                'headerOptions' => ['style' => 'width:120px'],
            ],
            [
                'label' => Yii::t('front-end', 'Total Price'),
                'value' => function($model) {
                    return $model['price'] * $model['amount'];
                },
                'headerOptions' => ['style' => 'width:80px'],
            ],
            [
                'format' => 'html',
                'value' => function($model) {
                    return Html::img(Yii::getAlias('@phonesImgUrl').'/'.$model['img'],
                        ['width' => '100px']);
                },
                'headerOptions' => ['style' => 'width:80px'],
            ],
            [  
                'class' => 'yii\grid\ActionColumn',
                'contentOptions' => ['style' => 'width:260px;'],
                'header'=>'Actions',
                'template' => '{Plus} {Minus} {Confirm} {View}',
                'buttons' => [
                    
                    //confirm button
                    'Confirm' => function ($url, $model) {
                        if(empty($model['confirmed'])) {
                            return Html::a(Yii::t('front-end', 'Confirm'),
                                false, 
                                [
                                    'value' => (Yii::$app->user->isGuest) 
                                        ? Url::to(['/users/login', 'confirm_action' => true]) 
                                        : Url::to(['/cart/payment']),
                                    'class'=>'btn btn-primary cart_action_btn confirm_order_button',
                                ]
                            );
                        }
                        return '';
                    },
                            
                    //plus button
                    'Plus' => function ($url, $model) {
                        if(empty($model['confirmed'])) {
                            return Html::a('+',
                                ['/cart/add', 'id' => $model['id']], 
                                [
                                    'class'=>'btn btn-success cart_action_btn'
                                ]
                            );
                        }
                        return '';
                    },
                    //minus button
                    'Minus' => function ($url, $model) {
                        if(empty($model['confirmed'])) {
                            return Html::a('-',
                                ['/cart/minus', 'id' => $model['id']], 
                                [
                                    'class'=>'btn btn-danger cart_action_btn'
                                ]
                            );
                        }
                        return '';
                    },
                            
                    //view button
                    'View' => function ($url, $model) {
                        if(!empty($model['confirmed'])) {
                            return Html::a(Yii::t('front-end', 'View'),
                                ['/cart/view', 'id'=>$model['id']],
                                [
                                    'class'=>'btn btn-primary cart_action_btn', 
                                ]
                            );
                        }
                        return '';
                    },
                ],
            ]
        ],
        'showOnEmpty' => false,
    ]); ?>
    <?php Modal::begin([
            'id' => 'confirm_modal',
            'size' => 'modal-md'
        ]);
        
        echo '<div id="confirm_modal_content" class="clearfix text-center"></div>';

        Modal::end();
    ?>
</div>

frontend/views/cart/payment.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;
use yii\db\Query;
use yii\db\ActiveQuery;
use yii\web\Session;
use yii\bootstrap\Modal;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\ProductsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$session = Yii::$app->session;
$this->title = Yii::t('front-end', 'Payment');
?>
<div class="products-index">

    <h1><?= Html::encode($this->title) ?></h1>

</div>